In [23]:
# pip intall opencv-python
# pip install tensorflow==2.20.0

In [24]:
import cv2
from tensorflow.keras.models import load_model
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
import numpy

In [25]:
face_cas=cv2.CascadeClassifier('haarcascade_frontalface.xml')
face_cas

< cv2.CascadeClassifier 000001BCF5B1B830>

In [26]:
model=load_model('mask_recog.h5')

In [27]:
def face_mask_detector(frame):
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    faces=face_cas.detectMultiScale(gray,minNeighbors=4)
    print(faces)
    for (x,y,w,h) in faces:
        face_frame=frame[y:y+h,x:x+w]
        print(face_frame.shape)
        face_frame=cv2.cvtColor(face_frame,cv2.COLOR_BGR2RGB)
        face_frame=cv2.resize(face_frame,(224,224))
        face_frame=face_frame.reshape(1,224,224,3)
        face_frame=preprocess_input(face_frame)
        pred=model.predict(face_frame)[0]
        print(pred)
        mask,without_mask=pred
        label="With Mask" if mask>without_mask else "Without Mask"
        cv2.putText(frame,label,(x,y),cv2.FONT_HERSHEY_COMPLEX,.5,(0,0,255),2)
        cv2.rectangle(frame,(x,y),(x+w,y+h),(255,0,0),2)
    return frame

In [28]:
# img=cv2.imread("with_mask.jfif")
# prediction=face_mask_detector(img)
# cv2.imshow("PREDICTION",prediction)
# cv2.waitKey()
# cv2.destroyAllWindows()

In [29]:
img=cv2.imread("without_mask.jfif")
prediction=face_mask_detector(img)
cv2.imshow("PREDICTION",prediction)
cv2.waitKey()
cv2.destroyAllWindows()

[[17 36 94 94]]
(94, 94, 3)
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[7.8571055e-08 9.9999988e-01]


In [30]:
video=cv2.VideoCapture(0)
while True:
    suc,frame=video.read()
    if not suc:
        break
    frame=face_mask_detector(frame)
    cv2.imshow("Face Mask Detection",frame)
    if cv2.waitKey(1) & 0XFF==ord('a'):
        break
video.release()
cv2.destroyAllWindows()

[[326 216 157 157]]
(157, 157, 3)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step
[2.3774833e-06 9.9999762e-01]
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
[[391 223 152 152]]
(152, 152, 3)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
[1.2056628e-06 9.9999881e-01]
[[363 215 173 173]]
(173, 173, 3)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
[6.203771e-06 9.999938e-01]
[[337 220 163 163]]
(163, 163, 3)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
[3.3261327e-05 